name: michitray CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  generate-test-file:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Pydub
        run: python3 -m pip install pydub
      - name: Install ffmpeg
        run: sudo apt update -y && sudo apt install -y ffmpeg
      - name: Generate Test Files
        run: python3 scripts/generate-silence.py
      - uses: actions/upload-artifact@v4
        with:
          name: silence.mp3
          path: mp3/silence.mp3

  build-debug:

    runs-on: ubuntu-latest

    needs: generate-test-file

    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
      with:
        name: silence.mp3
        path: mp3
    - name: Install Meson
      run: python3 -m pip install meson ninja
    - name: Install Dependencies
      run: |
        sudo apt update -y && \
        sudo apt install -y build-essential libconfig-dev libgtk-3-dev libayatana-appindicator3-dev cmake
    - name: LS
      run: ls mp3
    - name: Setup
      run: meson setup build
    - name: Compile
      run: meson compile -C build

  build-release:

    runs-on: ubuntu-latest

    needs: generate-test-file

    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
      with:
        name: silence.mp3
        path: mp3
    - name: Install Meson
      run: python3 -m pip install meson ninja
    - name: Install Dependencies
      run: |
        sudo apt update -y && \
        sudo apt install -y build-essential libconfig-dev libgtk-3-dev libayatana-appindicator3-dev cmake ffmpeg
    - name: Setup
      run: meson setup --buildtype=release build
    - name: Compile
      run: meson compile -C build

  test:

    runs-on: ubuntu-latest

    needs: [build-debug,generate-test-file]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: silence.mp3
          path: mp3
      - name: Install Meson
        run: python3 -m pip install meson ninja
      - name: Install Dependencies
        run: |
          sudo apt update -y && \
          sudo apt install -y build-essential libconfig-dev libgtk-3-dev libayatana-appindicator3-dev cmake ffmpeg
      - name: Setup
        run: meson setup build
      - name: Test
        run: meson test -C build
